{% set name = "hiclass" %}
{% set version = "4.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05e5af3fd1bae68d0ac63034a2ef1ebec29bf29b5b47942e021499e4ee5430a0

build:
  noarch: python
  number: 0
  entry_points:
    - hiclass = hiclass.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.9
    - pip
  run:
    - python >=3.7,<3.9
    - networkx
    - numpy
    - scikit-learn
    - ray-core

test:
  imports:
    - hiclass
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/mirand863/hiclass
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Hierarchical Classification Library
  description: |
    HiClass is a library for hierarchical classification which
    is inspired in scikit-learn's usability and is optimized
    for speed. It is pure python code compatible with
    Python 3.8+ and requires networkx, numpy and scikit-learn.
  doc_url: https://hiclass.readthedocs.io/
  dev_url: https://github.com/mirand863/hiclass

extra:
  recipe-maintainers:
    - mirand863
